In [106]:
#question 1
import numpy as np
b = np.array([1,2,3,])
b.tolist()

print(b)

[1 2 3]


In [84]:
#question 2
import numpy as np
a = np.array([[0,1,2],[3,4,5],[6,7,8]])
a.trace()


12

In [97]:
#question 3
import numpy as np
c = np.array([[1,2],[3,5]])
x = 2
print(c[c>x])

[3 5]


In [108]:
#question 4
import numpy as np
a = np.array([[1,2],[3,4]])
b = np.array([[1,2],[3,4]])
c = np.add(a,b)
print(c)

[[2 4]
 [6 8]]


In [110]:
#question 5
import numpy as np
a = np.array([[1,2],[3,4]])

y = a.mean()

print(a-y)

[[-1.5 -0.5]
 [ 0.5  1.5]]
